// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZcU5vOTZtD3g-aybCHemcjIfKxrWxLp0',
    appId: '1:343143480425:web:f91f051548327c360d76f8',
    messagingSenderId: '343143480425',
    projectId: 'smartdrive-8a6a9',
    authDomain: 'smartdrive-8a6a9.firebaseapp.com',
    storageBucket: 'smartdrive-8a6a9.firebasestorage.app',
    measurementId: 'G-5FLHJ4Y1WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxRT1RmSChLbt-wA1wP2ssyl7qM35XEAo',
    appId: '1:343143480425:android:a198df99dd94fab60d76f8',
    messagingSenderId: '343143480425',
    projectId: 'smartdrive-8a6a9',
    storageBucket: 'smartdrive-8a6a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJYD1GYGdohhQif_P3wj46n0vHxFIdVj0',
    appId: '1:343143480425:ios:09fcf5a9ad0339fb0d76f8',
    messagingSenderId: '343143480425',
    projectId: 'smartdrive-8a6a9',
    storageBucket: 'smartdrive-8a6a9.firebasestorage.app',
    iosBundleId: 'com.example.smartDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJYD1GYGdohhQif_P3wj46n0vHxFIdVj0',
    appId: '1:343143480425:ios:09fcf5a9ad0339fb0d76f8',
    messagingSenderId: '343143480425',
    projectId: 'smartdrive-8a6a9',
    storageBucket: 'smartdrive-8a6a9.firebasestorage.app',
    iosBundleId: 'com.example.smartDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZcU5vOTZtD3g-aybCHemcjIfKxrWxLp0',
    appId: '1:343143480425:web:f826b9c067003afb0d76f8',
    messagingSenderId: '343143480425',
    projectId: 'smartdrive-8a6a9',
    authDomain: 'smartdrive-8a6a9.firebaseapp.com',
    storageBucket: 'smartdrive-8a6a9.firebasestorage.app',
    measurementId: 'G-VKJ1QFJDLR',
  );
}
